disabled_rules:
- trailing_whitespace
- class_delegate_protocol
- identifier_name
- redundant_objc_attribute
- todo
- trailing_comma
- vertical_parameter_alignment
- line_length
- force_try
- unused_optional_binding

opt_in_rules:
- empty_count
- empty_string
excluded:
- Carthage
- Pods
- SwiftLint/Common/3rdPartyLib
line_length:
    warning: 190
    error: 200
    ignores_function_declarations: true
    ignores_comments: true
    ignores_urls: true
function_body_length:
    warning: 300
    error: 500
function_parameter_count:
    warning: 10
    error: 12
type_body_length:
    warning: 300
    error: 500
file_length:
    warning: 1000
    error: 1500
    ignore_comment_only_lines: true
cyclomatic_complexity:
    warning: 15
    error: 25
reporter: "xcode"
